### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by cnjsdfcy** [grigory-rechistov/simbook#2]
Hi Grigory,

Is there a plan to convert the current Russian version to an English version for more can read?

Thanks,
Yu

**Comment by grigory-rechistov** [comment]
Hi Yu,

I was playing with an idea to translate at least some parts of my book to English. Unfortunately, I never got time nor funding to start it. 

The most recent book about virtual platforms in English is written by my colleagues:

Daniel Aarno, Jakob Engblom. Software and System Development Using Virtual Platforms — 346 p. — 2015 — Morgan Kaufman — ISBN 978-0-12-800725-9.

It covers several topics not mentioned in my book, but also lacks in-depth discussion of certain themes I would like to see covered in more details.

Link to PDF: http://libgen.li/item/index.php?md5=86A667565E71837486BE4DD7C4AE8B3B

**Comment by cnjsdfcy** [comment]
Grigory, thanks for the info.
Still look forward to your English version. ^_^
